

##use Master C# project
services:
    master:
      container_name: master
      image: deightma_master
      build:
        context: ./Master
        dockerfile: Dockerfile
      ports:
        - "5000:5552"
      networks:
        - distr-network
      environment:
        - "USE_DUMMY=false"
    bicubic_interpolation_service: 
      container_name: bicubic_interpolation_service
      image: deightma_bicubic_interpolation_service
      build:
        context: ./bicubic_interpolation_service
        dockerfile: Dockerfile
      ports:
        - "5555:8080"   ## this is for debug purposes, the service does not need to be exposed to the host at all
      networks:
        - distr-network
    coordinator:
      image: deightma_coordinator
      build:
        context: ./coordinator
        dockerfile: Dockerfile
      ports:
        - "5003:8080"       ## this is for debug purposes, the service does not need to be exposed to the host at all
      networks:
        - distr-network
      environment:
        - "ENVIRONMENT=Development"
      deploy:
        mode: replicated
        replicas: 1              ## this is needed as of now. Do not change this or the values will be distributed unevenly
      restart: always 
    nodecs:
      image: deightma_nodecs
      build:
        context: ./Node_cs
        dockerfile: Dockerfiles/aot/Dockerfile
      environment:
        - CLUSTER_ENVIRONMENT=Network
      networks:
        - distr-network
      deploy:
        mode: replicated
        replicas: 4              
networks:
  distr-network:
    driver: bridge