

##use Master C# project
services:
    master:
      container_name: master
      image: ghcr.io/saetch/deightma_master:latest
      build:
        context: ./Master
        dockerfile: Dockerfile
      ports:
        - "5000:8080"
      networks:
        - distr-network
    bicubic_interpolation_service: 
      container_name: bicubic_interpolation_service
      image: ghcr.io/saetch/bicubic_interpolation_service:latest
      build:
        context: ./bicubic_interpolation_service
        dockerfile: Dockerfile
      ports:
        - "5555:8080"   ## this is for debug purposes, the service does not need to be exposed to the host at all
      networks:
        - distr-network
    coordinator:
      image: ghcr.io/saetch/deightma_coordinator:latest
      build:
        context: ./coordinator
        dockerfile: Dockerfile
      ports:
        - "5003:8080"       ## this is for debug purposes, the service does not need to be exposed to the host at all
      networks:
        - distr-network
      environment:
        - "ENVIRONMENT=Development"
      deploy:
        mode: replicated
        replicas: 1              ## this is needed as of now. Do not change this or the values will be distributed unevenly. The coordinator is yet to be made replicatable
      restart: no 
      depends_on:
        - hasher_service
    nodecs:
      image: ghcr.io/saetch/deightma_nodecs:latest
      build:
        context: ./Node_cs
        dockerfile: Dockerfiles/aot/Dockerfile
      environment:
        - CLUSTER_ENVIRONMENT=Network
      networks:
        - distr-network
      deploy:
        mode: replicated
        replicas: 4        
      depends_on:
        - coordinator
    hasher_service:
      image: ghcr.io/saetch/hasher_service:latest
      ports:
        - "5002:8080"       ## this is for debug purposes, the service does not need to be exposed to the host at all
      build:
        context: ./hasher_service
        dockerfile: Dockerfile
      networks:
        - distr-network
      deploy:
        mode: replicated
        replicas: 1
networks:
  distr-network:
    driver: bridge