

##use Master C# project

version: '3.4'
services:
    master:
      container_name: master
      image: deightma_master
      build:
        context: ./Master
        dockerfile: Dockerfile
      ports:
        - "5000:5552"
      networks:
        - distr-network
      environment:
        - "USE_DUMMY=false"
    bicubic_interpolation_service: 
      container_name: bicubic_interpolation_service
      image: deightma_bicubic_interpolation_service
      build:
        context: ./bicubic_interpolation_service
        dockerfile: Dockerfile
      ports:
        - "5555:8080"   ## this is for debug purposes, the service does not need to be exposed to the host at all
      networks:
        - distr-network
    coordinator:
      image: deightma_coordinator
      build:
        context: ./coordinator
        dockerfile: Dockerfile
      ports:
        - "8080"       ## this is for debug purposes, the service does not need to be exposed to the host at all
      networks:
        - distr-network
      environment:
        - "ENVIRONMENT=Development"
      deploy:
        mode: replicated
        replicas: 1
      restart: always
networks:
  distr-network:
    driver: bridge