apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-ui
spec:
  selector:
    matchLabels:
      app: web-ui
  template:
    metadata:
      labels:
        app: web-ui
    spec:
      containers:
        - name: app
          image: ghcr.io/saetch/deightma_webui:latest
          ports:
            - containerPort: 80
              name: web-ui-port
          resources:
            requests:
              memory: "10Mi"
              cpu: "10m"
            limits:
              memory: "50Mi"
              cpu: "50m"