apiVersion: apps/v1
kind: Deployment
metadata:
  name: master
spec:
  selector:
    matchLabels:
      app: master
  template:
    metadata:
      labels:
        app: master
    spec:
      containers:
        - name: app
          image: ghcr.io/saetch/deightma_master:latest
          ports:
            - containerPort: 8080
              name: master-port
          env:
            - name: DB_HOST
              value: test-db
          resources:
            requests:
              memory: "20Mi"
              cpu: "10m"
            limits:
              memory: "100Mi"
              cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: master-service
spec:
  selector:
    app: master
  ports:
    - name: master-port
      protocol: TCP
      port: 5000
      targetPort: master-port
