apiVersion: apps/v1
kind: Deployment
metadata:
  name: d-nodecs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: d-nodecs
  template:
    metadata:
      labels:
        app: d-nodecs
    spec:
      containers:
        - name: app
          image: ghcr.io/saetch/deightma_nodecs:latest
          ports:
            - containerPort: 5552
              name: d-nodecs-p
          env:
            - name: DB_HOST
              value: test-db
          resources:
            requests:
              memory: "20Mi"
              cpu: "10m"
            limits:
              memory: "100Mi"
              cpu: "100m"
          env:
            - name: CLUSTER_ENVIRONMENT
              value: "pod"

