apiVersion: apps/v1
kind: Deployment
metadata:
  name: bicubic
spec:
  selector:
    matchLabels:
      app: bicubic
  template:
    metadata:
      labels:
        app: bicubic
    spec:
      containers:
        - name: app
          image: ghcr.io/saetch/deightma_bicubic_interpolation_service:latest
          ports:
            - containerPort: 8080
              name: bicubic-p
          env:
            - name: DB_HOST
              value: test-db
          resources:
            requests:
              memory: "20Mi"
              cpu: "10m"
            limits:
              memory: "100Mi"
              cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: bicubic
spec:
  selector:
    app: bicubic
  ports:
    - name: bicubic-p
      protocol: TCP
      port: 8080
      targetPort: bicubic-p
